version: '3'
 
services:
  jenkins:
    container_name: jenkins
    #image: docker.io/jenkins/jenkins:latest
    build: .
    restart: "always"
    ports:
      - "2000:8080" 
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      resources:
        limits:
          memory: 2000M
    networks:
      - dodropin_net

networks:
  dodropin_net:
    external: true
