#FROM nginx:alpine
FROM docker.io/nginx:latest

ADD conf.d /etc/nginx/conf.d
#ADD assets /var/www/assets
#ADD html /var/www/html
ADD assets /etc/nginx/assets
ADD html /etc/nginx/html
ADD html /usr/share/nginx/html
