version: "3"

services:
  nginx:
    container_name: nginx
    build: .
    #image: nginx
    ports:
        - 0.0.0.0:8080:80
    #volumes:
    #    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    #    - ./html:/usr/share/nginx/html
    #healthcheck:
    #    # neither curl or wget are in the nginx image
    #    #test: curl --fail http://localhost:8000/ping.html || exit 1
    #    test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8000/ping.html || exit 1"]
    #    interval: 60s
    #    retries: 5
    #    timeout: 10s
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - dodropin_net

networks:
  dodropin_net:
    external: true
