version: '3'

services:
  zookeeper:
    image: docker.io/wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    deploy:
      resources:
        limits:
          memory: 200M
    networks:
      - dodropin_net

  kafka:
    image: docker.io/wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
        - zookeeper
    deploy:
      resources:
        limits:
          memory: 1000M
    networks:
      - dodropin_net

networks:
  dodropin_net:
    external: true
