version: '3'
 
services:
  git-server:
    container_name: git-server
    image: docker.io/jkarlos/git-server-docker
    restart: always
    ports:
      - "2222:22" 
    volumes:
      - ./keys:/git-server/keys
      - ./repos:/git-server/repos
